# -*- coding: utf-8 -*-
"""customer_spend_analysis_using_k-means-clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xk2yKRLQjm3UPCJ4HL6zRxuiBtuN8T07
"""

#imploding the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#load the dataset to colab 
from google.colab import files
upoaded = files.upload()

#elements to as a dataset variable
dataset = pd.read_csv('customet_spent_analysis_kmc.csv')

#Summarizing the dataset
print(dataset.shape)
print(dataset.describe())
print(dataset.head(5))
print(dataset.tail(5))

#Segreating & zipping the dataset
Income = dataset['INCOME'].values
Spend = dataset['SPEND'].values
X = np.array(list(zip(Income,Spend)))
X

#finding the optimized k values
from sklearn.cluster import KMeans
wcss = []
for i in range(1,11):
  km=KMeans(n_clusters=i, random_state=0)
  km.fit(X)
  wcss.append(km.inertia_)
plt.plot(range(1,11),wcss,color="red",marker="8")
plt.title('Optimal k value')
plt.xlabel('No. of clusters')
plt.ylabel('wcss')
plt.show()

#fitting the k means to the dataset with k = 4
model=KMeans(n_clusters=4, random_state=0)
y_means = model.fit_predict(X)

#visualizing the clusers for k = 4 (clusters=1,2,3,4)
#1:customer with medium income and low spend 
#2:customer with high income and medium to high spend
#3:customer with low income 
#4:customer with medium income and high spend

plt.scatter(X[y_means==0,0],X[y_means==0,1],s=50, c='red',label='1')
plt.scatter(X[y_means==1,0],X[y_means==1,1],s=50, c='blue',label='2')
plt.scatter(X[y_means==2,0],X[y_means==2,1],s=50, c='green',label='3')
plt.scatter(X[y_means==3,0],X[y_means==3,1],s=50, c='violet',label='4')
plt.scatter(model.cluster_centers_[:,0], model.cluster_centers_[:,1],s=100,marker='s', c='gray', label='centroid')
plt.title('income spent analysis ')
plt.xlabel('income')
plt.ylabel('spent')
plt.legend()
plt.show()
print(" cluster 1:customer with medium income and low spend \n cluster 2:customer with high income and medium to high spend \n cluster 3:customer with low income  \n cluster 4:customer with medium income and high spend")